# Generated by Django 5.0 on 2023-12-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Ingrese una dirección de correo electrónico válido, personal y único.', max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('full_name', models.CharField(help_text='Ingrese su nombre completo tal como aparece en su documento de identidad.', max_length=50, verbose_name='Nombre completo')),
                ('identification_document', models.CharField(help_text='Ingrese el número de su documento de identidad, sin puntos ni guiones.', max_length=50, verbose_name='Documento de identidad')),
                ('is_passport', models.BooleanField(default=False, help_text='Marque esta opción si su documento de identidad es un passaporte.', verbose_name='Es pasaporte')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], help_text='Utilizado para personalizar programas de entrenamiento específicos.', max_length=1, null=True, verbose_name='Género')),
                ('birthdate', models.DateTimeField(help_text='Seleccione la fecha de su nacimiento.', verbose_name='Fecha de nacimiento')),
                ('health_history', models.TextField(blank=True, help_text='Indique si padece alguna enfermedad o patologia de salud que sea incompatible con el esfuerzo físico o la realización de ciertos ejercicios.', null=True, verbose_name='Historiañ de salud')),
                ('communication_preference', models.CharField(choices=[('T', 'Teléfono'), ('W', 'Whatsapp'), ('E', 'Email')], help_text='Escoja el canal por el cual desea que nos comuniquemos con usted.', max_length=1, verbose_name='Preferencia de comunicación')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('authorization_file', models.FileField(blank=True, null=True, upload_to='authorization/', verbose_name='Autorización parental')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es parte del equipo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_users_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
