# Generated by Django 5.0 on 2023-12-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='authorization_file',
            field=models.FileField(blank=True, help_text='Requerido solo si tiene entre 14 y 18 años.', null=True, upload_to='authorization/', verbose_name='Autorización parental'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(help_text='Seleccione la fecha de su nacimiento.', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='health_history',
            field=models.TextField(blank=True, help_text='Indique si padece alguna enfermedad o patologia de salud que sea incompatible con el esfuerzo físico o la realización de ciertos ejercicios.', null=True, verbose_name='Historial de salud'),
        ),
    ]
