# Generated by Django 4.2.3 on 2023-12-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0009_CustomUser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trainer',
            field=models.BooleanField(default=False, verbose_name='Es entrenador'),
        ),
    ]
